project_id: '567019'
api_token_env: CROWDIN_PERSONAL_TOKEN
export_languages:
  - pl-PL
preserve_hierarchy: true
files:
  - source: /i18n/pl/**/*
    translation: /i18n/%two_letters_code%/**/%original_file_name%
  - source: /docs/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
