/**
 * @copyright YetiForce S.A.
 * @license   YetiForce Public License 5.0 (licenses/LicenseEN.txt or yetiforce.com)
 * @author    Mariusz Krzaczkowski <m.krzaczkowski@yetiforce.com>
 */
module.exports = {
	docs: [
		{
			type: 'autogenerated',
			dirName: '.' // '.' means the current docs folder
		}
	]
};
