openapi: 3.0.0
info:
  title: 'YetiForce API for OAuth. Type: OAuth'
  description: ''
  termsOfService: 'https://yetiforce.com/'
  contact:
    name: 'Devs API Team'
    url: 'https://yetiforce.com/'
    email: devs@yetiforce.com
  license:
    name: 'YetiForce Public License'
    url: 'https://yetiforce.com/en/yetiforce/license'
  version: '0.1'
servers:
  -
    url: 'https://gitdeveloper.yetiforce.com'
    description: 'Demo server of the development version'
  -
    url: 'https://gitstable.yetiforce.com'
    description: 'Demo server of the latest stable version'
paths:
  /webservice/OAuth/MailAccount:
    get:
      summary: 'OAuth mail authorization api'
      operationId: 0037f4e5752f76f6199e8e3964ef6efb
      responses:
        '200':
          description: Result
externalDocs:
  description: 'Platform API Interactive Docs'
  url: 'https://doc.yetiforce.com/api/?urls.primaryName=OAuth'
