openapi: 3.0.0
info:
  title: 'YetiForce API for Token. Type: Token'
  description: ''
  termsOfService: 'https://yetiforce.com/'
  contact:
    name: 'Devs API Team'
    url: 'https://yetiforce.com/'
    email: devs@yetiforce.com
  license:
    name: 'YetiForce Public License'
    url: 'https://yetiforce.com/en/yetiforce/license'
  version: '0.1'
servers:
  -
    url: 'https://gitdeveloper.yetiforce.com'
    description: 'Demo server of the development version'
  -
    url: 'https://gitstable.yetiforce.com'
    description: 'Demo server of the latest stable version'
paths:
  '/webservice/Token/{token}':
    get:
      summary: 'Token support'
      description: 'Token support method.'
      operationId: 4b163213903e75b07d7f8b9bea561f2c
      parameters:
        -
          name: token
          in: path
          description: Token
          required: true
          schema:
            type: string
          example: vrm6bcA3fp2J0RB96AvDCAVsKv1MaMVbGQ1QbFtS5jr0DSXvUvc3ec08fMhCk7kd
      responses:
        '200':
          description: Result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token_Get_Report'
        '404':
          description: 'No token'
        '405':
          description: 'The token does not exist or has expired'
components:
  schemas:
    Token_Get_Report:
      title: Response
      description: Response
      type: string
      example: OK
externalDocs:
  description: 'Platform API Interactive Docs'
  url: 'https://doc.yetiforce.com/api/?urls.primaryName=Token'
